- name: ping the server 
  hosts: localhost
  become: yes
  tasks:
    - name: ping the server
      ping: #  ansible.builtin.ping
    - name:  install the package
      package:
        name: nginx
        state: present
    - name: debug the message
      debug:
        msg: " nginx is installed successfully"   
        
    - name:  start the service
      service:
        name: nginx
        state: started
        enabled: yes ### YamlMime:Achievements
    - name: debug the start message
      debug:
        msg: " nginx is started successfully"    
        
        

      
  


  
