- name: ping the server 
  hosts: localhost
  become: yes
  tasks:
    - name: ping the server
      ping: #  ansible.builtin.ping
    - name:  install the package
      ansible.builtin.package:
        name: nginx
        state: present
        
    - name:  start the service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes ### YamlMime:Achievements
        
        

      
  


  
