- name: install packages
  hosts: localhost
  connection: local
  tasks:
  - name: install packages
    package:
      name:  "{{ item.name }}"
      state: "{{ item.state }}"
    debug:
      msg: "installing {{ item }}"
    loop:
      - { name: git, state: present }
      - { name: python3, state: present }
      - { name: ansible, state: present }
      - { name: nginx, state: present }